# Check for lint error and auto correct them

name: Check for lint errors

on: ['push', 'pull_request']

jobs:
  lint_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check repo for lint errors
      run: ./scripts/git/cpplint_repo.py .
